version: '3.7'

services:
  sql:
    container_name: sql_test
    # lokasi source code
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    build:
      context: ./
      dockerfile: sql.Dockerfile
    # path untuk source di dalam docker
    image: sql_laravel:1.0
    ports:
      - 3306:3306

  nginx:
    container_name: con_laravel_sample
    # lokasi source code
    build:
      context: ./
      dockerfile: web.dockerfile
    # path untuk source di dalam docker
    volumes:
      - ./:/var/www
    image: webserver_laravel:1.0
    ports:
      - "80:80"

  app:
    container_name: app_laravel_sample
    build:
      context: ./
      dockerfile: app.dockerfile
    image: app_laravel:1.0
    volumes:
      - ./:/var/www